# Generated by Django 5.0.4 on 2025-02-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_wantmodel_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='wantmodel',
            name='username',
            field=models.CharField(blank=True, default='a', max_length=50, null=True),
        ),
    ]
