# Generated by Django 5.0.4 on 2025-02-24 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_wantmodel_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wantmodel',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
